# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-11-28 23:32
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('search_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='VinylQuery',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('query_image', models.ImageField(upload_to='')),
            ],
        ),
        migrations.DeleteModel(
            name='Image_upload',
        ),
    ]
