# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-12-13 21:25
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('search_app', '0002_auto_20161130_0045'),
    ]

    operations = [
        migrations.AddField(
            model_name='vinylquery',
            name='result_format',
            field=models.CharField(max_length=9000, null=True),
        ),
        migrations.AddField(
            model_name='vinylquery',
            name='result_thumb',
            field=models.URLField(null=True),
        ),
        migrations.AddField(
            model_name='vinylquery',
            name='result_title',
            field=models.CharField(max_length=9000, null=True),
        ),
    ]
