# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-12-26 20:40
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('search_app', '0004_remove_vinylquery_result_format'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='vinylquery',
            name='result_thumb',
        ),
        migrations.AddField(
            model_name='vinylquery',
            name='result_url',
            field=models.URLField(null=True),
        ),
    ]
